// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "id")]
        public SpacetimeDB.Identity Id;
        [DataMember(Name = "online")]
        public bool Online;

        public Player(
            SpacetimeDB.Identity Id,
            bool Online
        )
        {
            this.Id = Id;
            this.Online = Online;
        }

        public Player()
        {
        }
    }
}
